# CMake generated Testfile for 
# Source directory: /home/user/cmake-3.12.2/Tests/FindGTK2
# Build directory: /home/user/cmake-3.12.2/Tests/FindGTK2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GTK2Components.gtk "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gtk" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Components/gtk" "--build-generator" "Unix Makefiles" "--build-target" "gtk-all-libs" "--build-project" "gtk" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Components/gtk" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.glib "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/glib" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/glib" "--build-generator" "Unix Makefiles" "--build-project" "glib" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/glib" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gobject "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gobject" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gobject" "--build-generator" "Unix Makefiles" "--build-project" "gobject" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gobject" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gio "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gio" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gio" "--build-generator" "Unix Makefiles" "--build-project" "gio" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gio" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gmodule "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gmodule" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gmodule" "--build-generator" "Unix Makefiles" "--build-project" "gmodule" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gmodule" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gthread "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gthread" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gthread" "--build-generator" "Unix Makefiles" "--build-project" "gthread" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gthread" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.atk "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/atk" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/atk" "--build-generator" "Unix Makefiles" "--build-project" "atk" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/atk" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk_pixbuf "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gdk_pixbuf" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--build-generator" "Unix Makefiles" "--build-project" "gdk_pixbuf" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.cairo "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/cairo" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/cairo" "--build-generator" "Unix Makefiles" "--build-project" "cairo" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/cairo" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.pango "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/pango" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pango" "--build-generator" "Unix Makefiles" "--build-project" "pango" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pango" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.pangocairo "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/pangocairo" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--build-generator" "Unix Makefiles" "--build-project" "pangocairo" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangocairo" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoxft "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/pangoxft" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--build-generator" "Unix Makefiles" "--build-project" "pangoxft" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangoxft" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.pangoft2 "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/pangoft2" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--build-generator" "Unix Makefiles" "--build-project" "pangoft2" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/pangoft2" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gdk "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gdk" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gdk" "--build-generator" "Unix Makefiles" "--build-project" "gdk" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gdk" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
add_test(GTK2Targets.gtk "/home/user/cmake-3.12.2/bin/ctest" "--build-and-test" "/home/user/cmake-3.12.2/Tests/FindGTK2/gtk" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gtk" "--build-generator" "Unix Makefiles" "--build-project" "gtk" "--build-exe-dir" "/home/user/cmake-3.12.2/Tests/FindGTK2/GTK2Targets/gtk" "--force-new-ctest-process" "--test-command" "/home/user/cmake-3.12.2/bin/ctest" "-V")
